# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0003_auto_20170316_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
