# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0004_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='age_bac_max',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='age max. du bac'),
        ),
        migrations.AddField(
            model_name='settings',
            name='age_max',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='age max.'),
        ),
    ]
