# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0006_auto_20170317_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='filiere_dipolme',
            field=models.ManyToManyField(to='lp.FiliereDiplome'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='option_diplome',
            field=models.ManyToManyField(to='lp.OptionDiplome'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='type_diplome',
            field=models.ManyToManyField(to='lp.TypeDiplome'),
        ),
    ]
