# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0007_auto_20170318_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiondiplome',
            old_name='filiere_dipolme',
            new_name='filiere_diplome',
        ),
    ]
