# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0008_auto_20170318_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='filiere_dipolme',
            field=models.ManyToManyField(null=True, to='lp.FiliereDiplome'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='option_diplome',
            field=models.ManyToManyField(null=True, to='lp.OptionDiplome'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='type_diplome',
            field=models.ManyToManyField(null=True, to='lp.TypeDiplome'),
        ),
    ]
