# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0011_auto_20170318_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiere',
            old_name='filiere_dipolme',
            new_name='filieres_diplome',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='option_diplome',
            new_name='options_diplome',
        ),
        migrations.RenameField(
            model_name='filiere',
            old_name='type_diplome',
            new_name='types_diplome',
        ),
    ]
