# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0012_auto_20170318_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baremeage',
            options={'verbose_name': "barème d'âge", 'verbose_name_plural': "barème d'âge"},
        ),
        migrations.AlterModelOptions(
            name='baremeanneesdiplome',
            options={'verbose_name': "barème d'années de diplôme", 'verbose_name_plural': "barème d'années de diplôme"},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'filière'},
        ),
        migrations.AlterModelOptions(
            name='filierediplome',
            options={'verbose_name': 'filière de diplôme', 'verbose_name_plural': 'filières de diplôme'},
        ),
        migrations.AlterModelOptions(
            name='mentionbac',
            options={'verbose_name': 'mention de Bac', 'verbose_name_plural': 'mentions de Bac'},
        ),
        migrations.AlterModelOptions(
            name='optiondiplome',
            options={'verbose_name': 'option de diplôme', 'verbose_name_plural': 'options de diplôme'},
        ),
        migrations.AlterModelOptions(
            name='typebac',
            options={'verbose_name': 'type de Bac', 'verbose_name_plural': 'types de Bac'},
        ),
        migrations.AlterModelOptions(
            name='typediplome',
            options={'verbose_name': 'type de diplôme', 'verbose_name_plural': 'types de diplôme'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='note_preselection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='note de préselection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baremeage',
            name='note_preselection',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='note de préselection'),
        ),
        migrations.AlterField(
            model_name='baremeanneesdiplome',
            name='note_preselection',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='note de préselection'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='filierediplome',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='mentionbac',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='mentionbac',
            name='note_preselection',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='note de préselection'),
        ),
        migrations.AlterField(
            model_name='optiondiplome',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='typebac',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='typediplome',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='libellé'),
        ),
    ]
