# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0013_auto_20170318_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='option_diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lp.OptionDiplome'),
        ),
    ]
