# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0014_auto_20170318_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='filiere_diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lp.FiliereDiplome'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lp.User'),
        ),
    ]
