# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0015_auto_20170318_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
