# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0016_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='jeton_validation',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
