# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0017_auto_20170320_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='nb_redoublements',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sans redoublement'), (1, 'Un redoublement'), (2, 'Deux redoublements')], default=0, verbose_name='nombre de redoublements'),
        ),
        migrations.AlterField(
            model_name='baremeage',
            name='age_max',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='âge max.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='age_bac_max',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='âge max. du bac'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='age_max',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='âge max.'),
        ),
    ]
