# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0018_auto_20170321_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baremeanneesdiplome',
            old_name='annees_max',
            new_name='nb_redoublements',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='nb_redoublements',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sans redoublement'), (1, 'Un redoublement'), (2, 'Deux redoublements ou plus...')], default=0, verbose_name='nombre de redoublements'),
        ),
    ]
