# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0019_auto_20170321_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='libelle_court',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='libellé court'),
        ),
        migrations.AlterField(
            model_name='baremeanneesdiplome',
            name='nb_redoublements',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='nombre de redoublements'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='filiere_choisie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lp.Filiere', verbose_name='filière choisie'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='mention_bac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lp.MentionBac', verbose_name='mention du Bac'),
        ),
    ]
