# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0020_auto_20170321_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='cin',
            field=models.CharField(max_length=50, verbose_name="code d'Identification National (CIN)"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='cne',
            field=models.CharField(max_length=50, verbose_name="code National d'Étudiant (CNE)"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='telephone_gsm',
            field=models.CharField(max_length=20, verbose_name='no. de téléphone GSM'),
        ),
    ]
