from django.http import HttpResponseRedirect
from django.urls import reverse

def filter_login(request):
    user = request.user
    if user.is_staff:
        return HttpResponseRedirect(reverse('admin:index'))
    elif not user.is_anonymous:
        return HttpResponseRedirect(reverse('lp:panel'))

def lp_settings():
    from .models import Settings
    settingsSet = Settings.objects.filter(id=1)
    if len(settingsSet) == 0:
        settings = Settings(id=1)
        settings.save()
        return settings
    else:
        return settingsSet[0]

class Countries:
    CHOICES = [
        ("afghanistan", "Afghanistan"),
        ("albanie", "Albanie"),
        ("antarctique", "Antarctique"),
        ("algérie", "Algérie"),
        ("samoa américaines", "Samoa Américaines"),
        ("andorre", "Andorre"),
        ("angola", "Angola"),
        ("antigua-et-barbuda", "Antigua-et-Barbuda"),
        ("azerbaïdjan", "Azerbaïdjan"),
        ("argentine", "Argentine"),
        ("australie", "Australie"),
        ("autriche", "Autriche"),
        ("bahamas", "Bahamas"),
        ("bahreïn", "Bahreïn"),
        ("bangladesh", "Bangladesh"),
        ("arménie", "Arménie"),
        ("barbade", "Barbade"),
        ("belgique", "Belgique"),
        ("bermudes", "Bermudes"),
        ("bhoutan", "Bhoutan"),
        ("bolivie", "Bolivie"),
        ("bosnie-herzégovine", "Bosnie-Herzégovine"),
        ("botswana", "Botswana"),
        ("île bouvet", "Île Bouvet"),
        ("brésil", "Brésil"),
        ("belize", "Belize"),
        ("territoire britannique de l'océan indien", "Territoire Britannique de l'Océan Indien"),
        ("îles salomon", "Îles Salomon"),
        ("îles vierges britanniques", "Îles Vierges Britanniques"),
        ("brunéi darussalam", "Brunéi Darussalam"),
        ("bulgarie", "Bulgarie"),
        ("myanmar", "Myanmar"),
        ("burundi", "Burundi"),
        ("bélarus", "Bélarus"),
        ("cambodge", "Cambodge"),
        ("cameroun", "Cameroun"),
        ("canada", "Canada"),
        ("cap-vert", "Cap-vert"),
        ("îles caïmanes", "Îles Caïmanes"),
        ("république centrafricaine", "République Centrafricaine"),
        ("sri lanka", "Sri Lanka"),
        ("tchad", "Tchad"),
        ("chili", "Chili"),
        ("chine", "Chine"),
        ("taïwan", "Taïwan"),
        ("île christmas", "Île Christmas"),
        ("îles cocos (keeling)", "Îles Cocos (Keeling)"),
        ("colombie", "Colombie"),
        ("comores", "Comores"),
        ("mayotte", "Mayotte"),
        ("république du congo", "République du Congo"),
        ("république démocratique du congo", "République Démocratique du Congo"),
        ("îles cook", "Îles Cook"),
        ("costa rica", "Costa Rica"),
        ("croatie", "Croatie"),
        ("cuba", "Cuba"),
        ("chypre", "Chypre"),
        ("république tchèque", "République Tchèque"),
        ("bénin", "Bénin"),
        ("danemark", "Danemark"),
        ("dominique", "Dominique"),
        ("république dominicaine", "République Dominicaine"),
        ("équateur", "Équateur"),
        ("el salvador", "El Salvador"),
        ("guinée équatoriale", "Guinée Équatoriale"),
        ("éthiopie", "Éthiopie"),
        ("érythrée", "Érythrée"),
        ("estonie", "Estonie"),
        ("îles féroé", "Îles Féroé"),
        ("îles (malvinas) falkland", "Îles (malvinas) Falkland"),
        ("géorgie du sud et les îles sandwich du sud", "Géorgie du Sud et les Îles Sandwich du Sud"),
        ("fidji", "Fidji"),
        ("finlande", "Finlande"),
        ("îles åland", "Îles Åland"),
        ("france", "France"),
        ("guyane française", "Guyane Française"),
        ("polynésie française", "Polynésie Française"),
        ("terres australes françaises", "Terres Australes Françaises"),
        ("djibouti", "Djibouti"),
        ("gabon", "Gabon"),
        ("géorgie", "Géorgie"),
        ("gambie", "Gambie"),
        ("territoire palestinien occupé", "Territoire Palestinien Occupé"),
        ("allemagne", "Allemagne"),
        ("ghana", "Ghana"),
        ("gibraltar", "Gibraltar"),
        ("kiribati", "Kiribati"),
        ("grèce", "Grèce"),
        ("groenland", "Groenland"),
        ("grenade", "Grenade"),
        ("guadeloupe", "Guadeloupe"),
        ("guam", "Guam"),
        ("guatemala", "Guatemala"),
        ("guinée", "Guinée"),
        ("guyana", "Guyana"),
        ("haïti", "Haïti"),
        ("îles heard et mcdonald", "Îles Heard et Mcdonald"),
        ("saint-siège (état de la cité du vatican)", "Saint-Siège (état de la Cité du Vatican)"),
        ("honduras", "Honduras"),
        ("hong-kong", "Hong-Kong"),
        ("hongrie", "Hongrie"),
        ("islande", "Islande"),
        ("inde", "Inde"),
        ("indonésie", "Indonésie"),
        ("république islamique d'iran", "République Islamique d'Iran"),
        ("iraq", "Iraq"),
        ("irlande", "Irlande"),
        ("israël", "Israël"),
        ("italie", "Italie"),
        ("côte d'ivoire", "Côte d'Ivoire"),
        ("jamaïque", "Jamaïque"),
        ("japon", "Japon"),
        ("kazakhstan", "Kazakhstan"),
        ("jordanie", "Jordanie"),
        ("kenya", "Kenya"),
        ("république populaire démocratique de corée", "République Populaire Démocratique de Corée"),
        ("république de corée", "République de Corée"),
        ("koweït", "Koweït"),
        ("kirghizistan", "Kirghizistan"),
        ("république démocratique populaire lao", "République Démocratique Populaire Lao"),
        ("liban", "Liban"),
        ("lesotho", "Lesotho"),
        ("lettonie", "Lettonie"),
        ("libéria", "Libéria"),
        ("jamahiriya arabe libyenne", "Jamahiriya Arabe Libyenne"),
        ("liechtenstein", "Liechtenstein"),
        ("lituanie", "Lituanie"),
        ("luxembourg", "Luxembourg"),
        ("macao", "Macao"),
        ("madagascar", "Madagascar"),
        ("malawi", "Malawi"),
        ("malaisie", "Malaisie"),
        ("maldives", "Maldives"),
        ("mali", "Mali"),
        ("malte", "Malte"),
        ("martinique", "Martinique"),
        ("mauritanie", "Mauritanie"),
        ("maurice", "Maurice"),
        ("mexique", "Mexique"),
        ("monaco", "Monaco"),
        ("mongolie", "Mongolie"),
        ("république de moldova", "République de Moldova"),
        ("montserrat", "Montserrat"),
        ("maroc", "Maroc"),
        ("mozambique", "Mozambique"),
        ("oman", "Oman"),
        ("namibie", "Namibie"),
        ("nauru", "Nauru"),
        ("népal", "Népal"),
        ("pays-bas", "Pays-Bas"),
        ("antilles néerlandaises", "Antilles Néerlandaises"),
        ("aruba", "Aruba"),
        ("nouvelle-calédonie", "Nouvelle-Calédonie"),
        ("vanuatu", "Vanuatu"),
        ("nouvelle-zélande", "Nouvelle-Zélande"),
        ("nicaragua", "Nicaragua"),
        ("niger", "Niger"),
        ("nigéria", "Nigéria"),
        ("niué", "Niué"),
        ("île norfolk", "Île Norfolk"),
        ("norvège", "Norvège"),
        ("îles mariannes du nord", "Îles Mariannes du Nord"),
        ("îles mineures éloignées des états-unis", "Îles Mineures Éloignées des États-Unis"),
        ("états fédérés de micronésie", "États Fédérés de Micronésie"),
        ("îles marshall", "Îles Marshall"),
        ("palaos", "Palaos"),
        ("pakistan", "Pakistan"),
        ("panama", "Panama"),
        ("papouasie-nouvelle-guinée", "Papouasie-Nouvelle-Guinée"),
        ("paraguay", "Paraguay"),
        ("pérou", "Pérou"),
        ("philippines", "Philippines"),
        ("pitcairn", "Pitcairn"),
        ("pologne", "Pologne"),
        ("portugal", "Portugal"),
        ("guinée-bissau", "Guinée-Bissau"),
        ("timor-leste", "Timor-Leste"),
        ("porto rico", "Porto Rico"),
        ("qatar", "Qatar"),
        ("réunion", "Réunion"),
        ("roumanie", "Roumanie"),
        ("fédération de russie", "Fédération de Russie"),
        ("rwanda", "Rwanda"),
        ("sainte-hélène", "Sainte-Hélène"),
        ("saint-kitts-et-nevis", "Saint-Kitts-et-Nevis"),
        ("anguilla", "Anguilla"),
        ("sainte-lucie", "Sainte-Lucie"),
        ("saint-pierre-et-miquelon", "Saint-Pierre-et-Miquelon"),
        ("saint-vincent-et-les grenadines", "Saint-Vincent-et-les Grenadines"),
        ("saint-marin", "Saint-Marin"),
        ("sao tomé-et-principe", "Sao Tomé-et-Principe"),
        ("arabie saoudite", "Arabie Saoudite"),
        ("sénégal", "Sénégal"),
        ("seychelles", "Seychelles"),
        ("sierra leone", "Sierra Leone"),
        ("singapour", "Singapour"),
        ("slovaquie", "Slovaquie"),
        ("viet nam", "Viet Nam"),
        ("slovénie", "Slovénie"),
        ("somalie", "Somalie"),
        ("afrique du sud", "Afrique du Sud"),
        ("zimbabwe", "Zimbabwe"),
        ("espagne", "Espagne"),
        ("sahara occidental", "Sahara Occidental"),
        ("soudan", "Soudan"),
        ("suriname", "Suriname"),
        ("svalbard etîle jan mayen", "Svalbard etÎle Jan Mayen"),
        ("swaziland", "Swaziland"),
        ("suède", "Suède"),
        ("suisse", "Suisse"),
        ("république arabe syrienne", "République Arabe Syrienne"),
        ("tadjikistan", "Tadjikistan"),
        ("thaïlande", "Thaïlande"),
        ("togo", "Togo"),
        ("tokelau", "Tokelau"),
        ("tonga", "Tonga"),
        ("trinité-et-tobago", "Trinité-et-Tobago"),
        ("émirats arabes unis", "Émirats Arabes Unis"),
        ("tunisie", "Tunisie"),
        ("turquie", "Turquie"),
        ("turkménistan", "Turkménistan"),
        ("îles turks et caïques", "Îles Turks et Caïques"),
        ("tuvalu", "Tuvalu"),
        ("ouganda", "Ouganda"),
        ("ukraine", "Ukraine"),
        ("l'ex-république yougoslave de macédoine", "L'ex-République Yougoslave de Macédoine"),
        ("égypte", "Égypte"),
        ("royaume-uni", "Royaume-Uni"),
        ("île de man", "Île de Man"),
        ("république-unie de tanzanie", "République-Unie de Tanzanie"),
        ("états-unis", "États-Unis"),
        ("îles vierges des états-unis", "Îles Vierges des États-Unis"),
        ("burkina faso", "Burkina Faso"),
        ("uruguay", "Uruguay"),
        ("ouzbékistan", "Ouzbékistan"),
        ("venezuela", "Venezuela"),
        ("wallis et futuna", "Wallis et Futuna"),
        ("samoa", "Samoa"),
        ("yémen", "Yémen"),
        ("serbie-et-monténégro", "Serbie-et-Monténégro"),
        ("zambie", "Zambie"),
    ]
    LIST = {
        "afghanistan": "Afghanistan",
        "albanie": "Albanie",
        "antarctique": "Antarctique",
        "algérie": "Algérie",
        "samoa américaines": "Samoa Américaines",
        "andorre": "Andorre",
        "angola": "Angola",
        "antigua-et-barbuda": "Antigua-et-Barbuda",
        "azerbaïdjan": "Azerbaïdjan",
        "argentine": "Argentine",
        "australie": "Australie",
        "autriche": "Autriche",
        "bahamas": "Bahamas",
        "bahreïn": "Bahreïn",
        "bangladesh": "Bangladesh",
        "arménie": "Arménie",
        "barbade": "Barbade",
        "belgique": "Belgique",
        "bermudes": "Bermudes",
        "bhoutan": "Bhoutan",
        "bolivie": "Bolivie",
        "bosnie-herzégovine": "Bosnie-Herzégovine",
        "botswana": "Botswana",
        "île bouvet": "Île Bouvet",
        "brésil": "Brésil",
        "belize": "Belize",
        "territoire britannique de l'océan indien": "Territoire Britannique de l'Océan Indien",
        "îles salomon": "Îles Salomon",
        "îles vierges britanniques": "Îles Vierges Britanniques",
        "brunéi darussalam": "Brunéi Darussalam",
        "bulgarie": "Bulgarie",
        "myanmar": "Myanmar",
        "burundi": "Burundi",
        "bélarus": "Bélarus",
        "cambodge": "Cambodge",
        "cameroun": "Cameroun",
        "canada": "Canada",
        "cap-vert": "Cap-vert",
        "îles caïmanes": "Îles Caïmanes",
        "république centrafricaine": "République Centrafricaine",
        "sri lanka": "Sri Lanka",
        "tchad": "Tchad",
        "chili": "Chili",
        "chine": "Chine",
        "taïwan": "Taïwan",
        "île christmas": "Île Christmas",
        "îles cocos (keeling)": "Îles Cocos (Keeling)",
        "colombie": "Colombie",
        "comores": "Comores",
        "mayotte": "Mayotte",
        "république du congo": "République du Congo",
        "république démocratique du congo": "République Démocratique du Congo",
        "îles cook": "Îles Cook",
        "costa rica": "Costa Rica",
        "croatie": "Croatie",
        "cuba": "Cuba",
        "chypre": "Chypre",
        "république tchèque": "République Tchèque",
        "bénin": "Bénin",
        "danemark": "Danemark",
        "dominique": "Dominique",
        "république dominicaine": "République Dominicaine",
        "équateur": "Équateur",
        "el salvador": "El Salvador",
        "guinée équatoriale": "Guinée Équatoriale",
        "éthiopie": "Éthiopie",
        "érythrée": "Érythrée",
        "estonie": "Estonie",
        "îles féroé": "Îles Féroé",
        "îles (malvinas) falkland": "Îles (malvinas) Falkland",
        "géorgie du sud et les îles sandwich du sud": "Géorgie du Sud et les Îles Sandwich du Sud",
        "fidji": "Fidji",
        "finlande": "Finlande",
        "îles åland": "Îles Åland",
        "france": "France",
        "guyane française": "Guyane Française",
        "polynésie française": "Polynésie Française",
        "terres australes françaises": "Terres Australes Françaises",
        "djibouti": "Djibouti",
        "gabon": "Gabon",
        "géorgie": "Géorgie",
        "gambie": "Gambie",
        "territoire palestinien occupé": "Territoire Palestinien Occupé",
        "allemagne": "Allemagne",
        "ghana": "Ghana",
        "gibraltar": "Gibraltar",
        "kiribati": "Kiribati",
        "grèce": "Grèce",
        "groenland": "Groenland",
        "grenade": "Grenade",
        "guadeloupe": "Guadeloupe",
        "guam": "Guam",
        "guatemala": "Guatemala",
        "guinée": "Guinée",
        "guyana": "Guyana",
        "haïti": "Haïti",
        "îles heard et mcdonald": "Îles Heard et Mcdonald",
        "saint-siège (état de la cité du vatican)": "Saint-Siège (état de la Cité du Vatican)",
        "honduras": "Honduras",
        "hong-kong": "Hong-Kong",
        "hongrie": "Hongrie",
        "islande": "Islande",
        "inde": "Inde",
        "indonésie": "Indonésie",
        "république islamique d'iran": "République Islamique d'Iran",
        "iraq": "Iraq",
        "irlande": "Irlande",
        "israël": "Israël",
        "italie": "Italie",
        "côte d'ivoire": "Côte d'Ivoire",
        "jamaïque": "Jamaïque",
        "japon": "Japon",
        "kazakhstan": "Kazakhstan",
        "jordanie": "Jordanie",
        "kenya": "Kenya",
        "république populaire démocratique de corée": "République Populaire Démocratique de Corée",
        "république de corée": "République de Corée",
        "koweït": "Koweït",
        "kirghizistan": "Kirghizistan",
        "république démocratique populaire lao": "République Démocratique Populaire Lao",
        "liban": "Liban",
        "lesotho": "Lesotho",
        "lettonie": "Lettonie",
        "libéria": "Libéria",
        "jamahiriya arabe libyenne": "Jamahiriya Arabe Libyenne",
        "liechtenstein": "Liechtenstein",
        "lituanie": "Lituanie",
        "luxembourg": "Luxembourg",
        "macao": "Macao",
        "madagascar": "Madagascar",
        "malawi": "Malawi",
        "malaisie": "Malaisie",
        "maldives": "Maldives",
        "mali": "Mali",
        "malte": "Malte",
        "martinique": "Martinique",
        "mauritanie": "Mauritanie",
        "maurice": "Maurice",
        "mexique": "Mexique",
        "monaco": "Monaco",
        "mongolie": "Mongolie",
        "république de moldova": "République de Moldova",
        "montserrat": "Montserrat",
        "maroc": "Maroc",
        "mozambique": "Mozambique",
        "oman": "Oman",
        "namibie": "Namibie",
        "nauru": "Nauru",
        "népal": "Népal",
        "pays-bas": "Pays-Bas",
        "antilles néerlandaises": "Antilles Néerlandaises",
        "aruba": "Aruba",
        "nouvelle-calédonie": "Nouvelle-Calédonie",
        "vanuatu": "Vanuatu",
        "nouvelle-zélande": "Nouvelle-Zélande",
        "nicaragua": "Nicaragua",
        "niger": "Niger",
        "nigéria": "Nigéria",
        "niué": "Niué",
        "île norfolk": "Île Norfolk",
        "norvège": "Norvège",
        "îles mariannes du nord": "Îles Mariannes du Nord",
        "îles mineures éloignées des états-unis": "Îles Mineures Éloignées des États-Unis",
        "états fédérés de micronésie": "États Fédérés de Micronésie",
        "îles marshall": "Îles Marshall",
        "palaos": "Palaos",
        "pakistan": "Pakistan",
        "panama": "Panama",
        "papouasie-nouvelle-guinée": "Papouasie-Nouvelle-Guinée",
        "paraguay": "Paraguay",
        "pérou": "Pérou",
        "philippines": "Philippines",
        "pitcairn": "Pitcairn",
        "pologne": "Pologne",
        "portugal": "Portugal",
        "guinée-bissau": "Guinée-Bissau",
        "timor-leste": "Timor-Leste",
        "porto rico": "Porto Rico",
        "qatar": "Qatar",
        "réunion": "Réunion",
        "roumanie": "Roumanie",
        "fédération de russie": "Fédération de Russie",
        "rwanda": "Rwanda",
        "sainte-hélène": "Sainte-Hélène",
        "saint-kitts-et-nevis": "Saint-Kitts-et-Nevis",
        "anguilla": "Anguilla",
        "sainte-lucie": "Sainte-Lucie",
        "saint-pierre-et-miquelon": "Saint-Pierre-et-Miquelon",
        "saint-vincent-et-les grenadines": "Saint-Vincent-et-les Grenadines",
        "saint-marin": "Saint-Marin",
        "sao tomé-et-principe": "Sao Tomé-et-Principe",
        "arabie saoudite": "Arabie Saoudite",
        "sénégal": "Sénégal",
        "seychelles": "Seychelles",
        "sierra leone": "Sierra Leone",
        "singapour": "Singapour",
        "slovaquie": "Slovaquie",
        "viet nam": "Viet Nam",
        "slovénie": "Slovénie",
        "somalie": "Somalie",
        "afrique du sud": "Afrique du Sud",
        "zimbabwe": "Zimbabwe",
        "espagne": "Espagne",
        "sahara occidental": "Sahara Occidental",
        "soudan": "Soudan",
        "suriname": "Suriname",
        "svalbard etîle jan mayen": "Svalbard etÎle Jan Mayen",
        "swaziland": "Swaziland",
        "suède": "Suède",
        "suisse": "Suisse",
        "république arabe syrienne": "République Arabe Syrienne",
        "tadjikistan": "Tadjikistan",
        "thaïlande": "Thaïlande",
        "togo": "Togo",
        "tokelau": "Tokelau",
        "tonga": "Tonga",
        "trinité-et-tobago": "Trinité-et-Tobago",
        "émirats arabes unis": "Émirats Arabes Unis",
        "tunisie": "Tunisie",
        "turquie": "Turquie",
        "turkménistan": "Turkménistan",
        "îles turks et caïques": "Îles Turks et Caïques",
        "tuvalu": "Tuvalu",
        "ouganda": "Ouganda",
        "ukraine": "Ukraine",
        "l'ex-république yougoslave de macédoine": "L'ex-République Yougoslave de Macédoine",
        "égypte": "Égypte",
        "royaume-uni": "Royaume-Uni",
        "île de man": "Île de Man",
        "république-unie de tanzanie": "République-Unie de Tanzanie",
        "états-unis": "États-Unis",
        "îles vierges des états-unis": "Îles Vierges des États-Unis",
        "burkina faso": "Burkina Faso",
        "uruguay": "Uruguay",
        "ouzbékistan": "Ouzbékistan",
        "venezuela": "Venezuela",
        "wallis et futuna": "Wallis et Futuna",
        "samoa": "Samoa",
        "yémen": "Yémen",
        "serbie-et-monténégro": "Serbie-et-Monténégro",
        "zambie": "Zambie",
    }
